# frontend/Dockerfile.dev

FROM node:18-alpine
WORKDIR /app

# Copia apenas os arquivos de dependência para aproveitar o cache do Docker
COPY package*.json ./
COPY yarn.lock ./

# Instala as dependências
RUN yarn install

# O resto do código será montado via volume
# Expõe a porta padrão do servidor de desenvolvimento do Vite
EXPOSE 5173

# Comando para iniciar o servidor de desenvolvimento
CMD ["yarn", "dev"]